// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type ClydeEmailUpdateRequest struct {
	ID        string
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	Email     string
	Code      string
}

type ClydeEmailVerificationRequest struct {
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	Code      string
}

type ClydePasskeyCredential struct {
	ID              string
	UserID          string
	Name            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CoseAlgorithmID int32
	PublicKey       []byte
}

type ClydePasswordResetRequest struct {
	ID        string
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	CodeHash  string
}

type ClydeSecurityKey struct {
	ID              string
	UserID          string
	Name            string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CoseAlgorithmID int32
	PublicKey       []byte
}

type ClydeUser struct {
	ID           string
	Email        string
	PasswordHash string
	RecoveryCode string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	Role         string
}

type ClydeUserTotpCredential struct {
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
	Key       []byte
}
