services:
  novus:
    container_name: clyde-novus
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ../.env

  mysql:
    container_name: clyde-mysql
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - clyde-mysql-data:/var/lib/mysql
    env_file:
      - ../.env

volumes:
  clyde-mysql-data:
    driver: local
