services:
  novus:
    container_name: clyde-novus
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ../.env

  postgres:
    container_name: clyde-postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - clyde-postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env

volumes:
  clyde-postgres-data:
    driver: local
